# Generated by Django 5.2.10 on 2026-01-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pomodoros', models.IntegerField(default=0)),
                ('focus_score', models.FloatField(default=0)),
            ],
        ),
    ]
