# Generated by Django 5.2.10 on 2026-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
